name: WizPhoto
favicon: null
layout_spectrum: 0.52444
typography_spectrum: 0.74154
title: Imaging Services by Wizphoto
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fffeff'
    - '#353e0f'
    - '#f7fa3d'
    - '#787a1e'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
